#!/usr/bin/env python3

import sys

def LCS(list1, list2):
  '''
     largest common substring algorithm
     return the common substring length matrix
  '''

  m = len(list1)
  n = len(list2)
  t = [ [ 0 for i in range(0, n + 1)] for row in range(0, m + 1)]
    
  for i in reversed(range(0, m)):
    for j in reversed(range(0, n)):
      if list1[i] == list2[j]:
        t[i][j] = 1 + t[i + 1][j + 1]
      else:
        t[i][j] = max((t[i + 1][j], t[i][j + 1]))
  return t

def generate_log(lst1, lst2):
  '''
     generate log that can be used for rollback from lst2 to lst1
  '''

  line_numbers1, list1 = compress(lst1)
  line_numbers2, list2 = compress(lst2)
  t = LCS(list1, list2)
  i = j = 0
  log = []
  while i < len(list1) and j < len(list2):
    if t[i][j] == t[i + 1][j]:
      log.append(("-", line_numbers1[i], list1[i]))
      i = i + 1
    elif t[i][j] == t[i][j + 1]:
      log.append(("+", line_numbers2[j]))
      j = j + 1
    else:
      log.append(("E", line_numbers1[i], line_numbers2[j]))
      i = i + 1
      j = j + 1
  while i < len(list1):
    log.append(("-", line_numbers1[i], list1[i]))
    i = i + 1
  while j < len(list2):
    log.append(("+", line_numbers2[j]))
    j = j + 1
  return log

def rollback(new_list, log, old_list_num):
  '''
     use logs to rollback the new list to the old list
  '''
  old_list = []
  line_num = 0
  for t in log:
    while line_num < t[1] - 1:
      old_list.append('')
      line_num += 1
    if t[0] == 'E':
      old_list.append(new_list[t[2]])
      line_num += 1
    elif t[0] == '-':
      old_list.append(t[2])
      line_num += 1

  while line_num < old_list_num:
    old_list.append('')
    line_num += 1
  return old_list
    
def compress(lst):
  '''
     remove the empty lines,
     return the non-empty lines and the corresponding line numbers in original list
  '''
  lines = []
  numbers = []
  for i, line in enumerate(lst):
    if line.strip() != '':
      lines.append(line)
      numbers.append(i)
  return numbers, lines

if __name__ == '__main__':
  '''
     usage: python3 diff.py file1 file2
     function: generate logs that can be used for restoring file sys.argv[1] from file named sys.argv[2]
     output: the generated file and logs
  '''

  list1 = [ line for line in open(sys.argv[1])]
  list2 = [ line for line in open(sys.argv[2])]

  print("-------", sys.argv[1], ":original file", "------------------------")
  for line in list1:
    print(line, end="")
  print("--------------------------end-----------------------\n")


  log = generate_log(list1, list2)
  old_list = rollback(list2, log, len(list1))
  print("-------", sys.argv[1], ":generated by log and ", sys.argv[2], "---------------")
  for line in old_list:
    print(line, end="")

  print("--------------------end\nlog details:")
  for t in log:
    print(t)
